version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: pipeline               # Your Lambda function name
        Alias: prod                  # Your alias name
        CurrentVersion: 1            # The current version of the function (version 1)
        TargetVersion: 2             # The new version that will be deployed
